version: "3.4"
services:
  backium:
    container_name: backium-server
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
      - mongodb
    environment:
      - BACKIUM_DB_URI=mongodb://mongodb:27017
      - BACKIUM_APP_PORT=8080
      - BACKIUM_REDIS_URI=redis:6379
      - BACKIUM_REDIS_PASSWORD=
  feeder:
    container_name: feeder
    build: ./scripts/feeder
    links:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb:27017
      - DB_NAME=testing
  redis:
    container_name: backium-redis
    image: "redis"
    ports:
      - "6379:6379"
  mongodb:
    container_name: backium-db
    hostname: mongodb
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
      ]
